{% set version = "70.0.1" %}

package:
  name: firefox-unbranded
  version: {{ version }}

source:
  url: https://queue.taskcluster.net/v1/task/BalSuXWkSq6jYDVY70rtIg/runs/0/artifacts/public/build/target.tar.bz2 # [linux64]
  # sha256: # [linux64]

  # fn: target.dmg  # [osx]
  # url: https://queue.taskcluster.net/v1/task/DCYVIUwIQmOq0CK8JsEVZQ/runs/0/artifacts/public/build/target.dmg # [osx]
  # sha256:   # [osx]

  # fn: firefox.msi  # [win]
  # url: https://queue.taskcluster.net/v1/task/dM5dTBdjS9eB9cuTDnCIrA/runs/0/artifacts/public/build/target.zip # [win]
  # sha256: # [win]

build:
  skip: True  # [not linux64]
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - selenium
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'Unbranded Firefox web browser. Typically used for testing add-ons in release versions of Firefox (https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds)'

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
