{% set name = "firefox-unbranded" %}
{% set version = "76.0.1" %}
{% set tag = "e2de5f11bc0afd9a3024d32b83cb9f0ada95717a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-release.revision.{{ tag }}.firefox.linux64-add-on-devel/artifacts/public/build/target.tar.bz2  # [linux64]
  sha256: d0e04e57d6999b0a35cc8b72ba94883bb7a779545352df42ceb9e392d356e549  # [linux64]

build:
  skip: True  # [not linux64]
  number: 0
  binary_relocation:
    - bin/firefox
  rpaths:
    - lib/
    - bin/FirefoxApp/
    - bin/FirefoxApp/gmp-clearkey/0.1/
    - bin/FirefoxApp/gtk2/
  rpaths_patcher: patchelf  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libice-devel') }}  # [linux]
    - {{ cdt('libsm-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxcomposite-devel') }}  # [linux]
    - {{ cdt('libxcursor-devel') }}  # [linux]
    - {{ cdt('libxdamage-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}  # [linux]
    - {{ cdt('libxinerama-devel') }}  # [linux]
    - {{ cdt('libxfixes-devel') }}  # [linux]
    - {{ cdt('libxrandr-devel') }}  # [linux]
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxtst-devel') }}  # [linux]
    - {{ cdt('mesa-libEGL-devel') }}  # [linux]
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

test:
  requires:
    - selenium
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'Unbranded Firefox web browser. Typically used for testing add-ons in release versions of Firefox (https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds)'

extra:
  recipe-maintainers:
    - birdsarah
